### PR TITLE
Fix phone normalization

### PR DESCRIPTION
**Pull request by AetherPrior**
Addresses #106 
- Change split from just '-' to '-' , '.'  , whitespace, based on the regex for the phone number.  
- Merge >2 splits to 2 splits

### CODE REVIEW

**Comment by huseinzol05** [comment]
Hah, nice!
Got some example to test your condition?

**Comment by AetherPrior** [comment]
031 313.212-2341 could be one example I suppose.

**Comment by AetherPrior** [comment]
@huseinzol05 oh, is there a place to update these tests?

**Comment by huseinzol05** [comment]
got unit tests at https://github.com/huseinzol05/malaya/tree/master/tests, required to run it manual, will add asap, thanks!

**Comment by AetherPrior** [comment]
Would it make sense if there's a good first issue for automatic tests? Currently, Jupyter notebooks don't work well with vcs

**Comment by huseinzol05** [comment]
Last time I did on March 2020, https://app.codecov.io/gh/huseinzol05/malaya, I wish can resume it back

**Comment by huseinzol05** [comment]
What is the expectation output from here? I got,

```python
import malaya
corrector = malaya.spell.probability()
normalizer = malaya.normalize.normalizer(corrector)
normalizer.normalize('031 313.212-2341')
```

output,

```text
{'normalize': 'tiga puluh satu tiga satu tiga, dua satu dua dua tiga empat satu',
 'date': {},
 'money': {}}
```

**Comment by AetherPrior** [comment]
@huseinzol05 
Apologies for the really late reply. I was using this as part of another project back in the day (I have credited you, it will be public soon I hope). Regarding the expected output, it looks like it's expected but I do not know Bahasa Malay so I can't tell.

**Pull request closed without merging**
